window:
  height: 720
  width: 1280

movement:
  right: 2.0
  left:  -2.0
  up: 10.0
  gravity: -0.5

stage:
  ground: 180

player:
  player1:
    health: 2000
    speed: 3.0
    damage: 50
  player2:
    health: 2000
    speed: 3.5
    damage: 100